### ISSUE TITLE
Error while enabling the Plugin in Napari

### ISSUE THREAD

**Issue by MalteMederacke** [AllenCellModeling/napari-aicsimageio#13]

**Comment by MalteMederacke** [comment]
Hi, 

Ive got a problem.

I can successfully download the napery-aicsimageio plugin (v0.2.0) via pip. After starting napari, I try to tick the plugins in the plug in menu (they appear there as installed.) But then an error pops up, I attached the log file.


Best,

Malte
[error.log](https://github.com/AllenCellModeling/napari-aicsimageio/files/6638320/error.log)

**Comment by JacksonMaxfield** [comment]
Hey! Sorry about this. It's because we released `aicsimageio==4.0.0` and didn't update the version pin on this. If you install `aicsimageio==3.3.4` you should be all set to go. I will try to release a new version of this that pins below v4.

**Comment by JacksonMaxfield** [comment]
Oh maybe not the same issue....

To be honest I want to entirely rewrite this plugin and haven't actively been developing it or maitaining it in a while. I made a fork for new v1.0 work that will pick up with aicsimageio v4 but that is also under-developed at the moment.

I am not sure when I will actively look into this.

**Comment by MalteMederacke** [comment]
Thanks for your fast reply!!

Okay, I need to analyse Zeiss leightsheet microscopy data. Any suggestion in how to tackle this under these circumatances?

**Comment by JacksonMaxfield** [comment]
I would say trying just `aicsimageio[czi]>=4.0.0`

Here is the readme: https://github.com/AllenCellModeling/aicsimageio

I would recommend reading the file with aicsimageio and then in python passing the numpy or dask array to `napari.view_image`

Note that we have had issues with light sheet data so hard to say really.
