### ISSUE TITLE
Installing the plugin requires aicspylibczi, which has a binary depend (libCZI)

### ISSUE THREAD

**Issue by psobolewskiPhD** [AllenCellModeling/napari-aicsimageio#21]
## Description
Installing the napari plugin requires aicsimageio[all], including aicspylibczi, which has a binary depend (libCZI). For architectures where this is available, I anticipate no problem. But, on others i can be an issue, because it has to be built locally. 

On Apple Silicon (arm64) I can
`pip install aicsimageio`
and
`pip install aicsimageio[lif]`
No issues. The latter is in fact all I'm interested in, as I have only LIF files.

However, installing the napari plugin only installs 0.2.0 and fails to update, due to lack of aicspylibczi. In my case, it's not something I actually care about or need, so the plugin failing is somewhat annoying and it's not clear what's happening.

## Expected Behavior

The napari plugin should work with just either base aicsimageio, or just aicsimageio[lif].

## Reproduction

Use napari plugins menu to install on non-x86/amd64 platform.

## Environment
```

napari: 0.4.10
Platform: macOS-11.5.2-arm64-arm-64bit
System: MacOS 11.5.2
Python: 3.9.6 | packaged by conda-forge | (default, Jul 6 2021, 08:51:19) [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.0
SciPy: 1.7.0
Dask: 2021.06.2
VisPy: 0.7.0

OpenGL:
- GL version: 2.1 Metal - 71.7.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Plugins:
- aicsimageio-in-memory: 0.3.5
- aicsimageio-out-of-memory: 0.3.5
- console: 0.0.3
- napari-properties-viewer: 0.0.2
- napari-skimage-regionprops: 0.1.2
- ome-types: 0.2.9
- scikit-image: 0.4.10
- svg: 0.1.5

```

**Comment by JacksonMaxfield** [comment]
Asked other aicsimageio devs about best way to handle this, the general consensus is to make `napari-aicsimageio` act the exact same as base `aicsimageio` and have all readers besides TIFF be additional imports / downloads.

**Comment by JacksonMaxfield** [comment]
Going to hold on this one for a bit. Gimme a couple more days I truly apologize.

**Comment by psobolewskiPhD** [comment]
No worries! It doesn't really affect me because I already have the compiled library, but the behavior is a bit annoying if one is napari-GUI-only.

**Comment by JacksonMaxfield** [comment]
Totally understand. We are trying to get cibuildwheel working which will make aicspylibczi installable by you anyway. This will likely go through but just so much to do in so little time!

**Comment by JacksonMaxfield** [comment]
@psobolewskiPhD can you try upgrading `aicspylibczi` to 3.0.3, we just released a new version which is built using cibuildwheel.

**Comment by JacksonMaxfield** [comment]
Just like a normal `pip install --upgrade aicspylibczi`

**Comment by psobolewskiPhD** [comment]
Success in my existing conda env.
```
Requirement already satisfied: aicspylibczi in ./Dev/miniforge3/envs/napari-test-old/lib/python3.9/site-packages (3.0.2)
Collecting aicspylibczi
  Downloading aicspylibczi-3.0.3-cp39-cp39-macosx_10_9_universal2.whl (560 kB)
     |████████████████████████████████| 560 kB 1.2 MB/s 
Requirement already satisfied: numpy>=1.14.1 in ./Dev/miniforge3/envs/napari-test-old/lib/python3.9/site-packages (from aicspylibczi) (1.21.0)
Installing collected packages: aicspylibczi
  Attempting uninstall: aicspylibczi
    Found existing installation: aicspylibczi 3.0.2
    Uninstalling aicspylibczi-3.0.2:
      Successfully uninstalled aicspylibczi-3.0.2
Successfully installed aicspylibczi-3.0.3
```

**Comment by JacksonMaxfield** [comment]
Woohoo! @toloudis looks like we did it!

**Comment by psobolewskiPhD** [comment]
Works perfectly in a clean env, although `imagecodecs` still needs to come from conda first, then `pip install aicsimageio[all]`
(Would go faster with pandas from conda too....)
