### ISSUE TITLE
Blank image with Light napari theme

### ISSUE THREAD

**Issue by psobolewskiPhD** [AllenCellModeling/napari-aicsimageio#22]
## Description
When using the Light napari theme and drag-n-dropping a LIF the image is blank, regardless of colormap, etc. Switching to Dark theme returns the image.
Light:
<img width="1546" alt="image" src="https://user-images.githubusercontent.com/76622105/132987223-67a33f9a-6da0-4799-a98e-b2588985dbc9.png">
Dark:
<img width="1546" alt="image" src="https://user-images.githubusercontent.com/76622105/132987225-4632c58a-6df1-44e2-b132-481897b9d19b.png">

## Expected Behavior

Image should be visible regardless of theme. Perhaps the colormap needs to be adjusted for optimal viewing, but it should not be a blank canvas.

## Reproduction

Drag-and-drop a LIF onto napari with napari-aicsimageio v 0.3.3 or 0.3.5 in napari 4.10 or 4.11
Change theme between Light and Dark.

## Environment

```

napari: 0.4.10
Platform: macOS-11.5.2-arm64-arm-64bit
System: MacOS 11.5.2
Python: 3.9.6 | packaged by conda-forge | (default, Jul 6 2021, 08:51:19) [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.0
SciPy: 1.7.0
Dask: 2021.06.2
VisPy: 0.7.0

OpenGL:
- GL version: 2.1 Metal - 71.7.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Plugins:
- aicsimageio-in-memory: 0.3.5
- aicsimageio-out-of-memory: 0.3.5
- console: 0.0.3
- napari-properties-viewer: 0.0.2
- napari-skimage-regionprops: 0.1.2
- ome-types: 0.2.9
- scikit-image: 0.4.10
- svg: 0.1.5

```

Also tested 0.3.5 of the plugin and napari 4.11. Same behavior.

**Comment by JacksonMaxfield** [comment]
To be honest... I have no idea what would be happening here.... Up until you tweeted I didn't know the light theme even existed. Can you post this issue on napari's github?

**Comment by JacksonMaxfield** [comment]
@psobolewskiPhD can I close this issue? It seems like this is a bug with napari and not with napari-aicsimageio (this plugin)
