### ISSUE TITLE
Meta issue: More robust method for downloading test resources

### ISSUE THREAD

**Issue by psobolewskiPhD** [AllenCellModeling/napari-aicsimageio#23]
## Use Case
I was quite surprised the test resources are nearly 3 Gb.
But this passed. It was frustrating though that it took me 4 tried (two different internet connections) to get them downloaded. Three times the download stalled and died:
```
[INFO: download_test_resources:  79 2021-09-13 10:41:00,793] Downloading test resources using top hash: 9b89503baf2bd3520be9223b25a2d500761cf8defcd67523e4ca3e388a4d03b1
Loading manifest: 100%|███████████████████████████| 37/37 [00:00<00:00, 50.4k/s]
Copying objects:  90%|██████████████████▉  | 2.47G/2.75G [36:50<04:06, 1.12MB/s]
[ERROR: download_test_resources:  95 2021-09-13 11:17:51,426] =============================================
[ERROR: download_test_resources:  99 2021-09-13 11:17:51,427] 

Read timeout on endpoint URL: "None"

[ERROR: download_test_resources: 100 2021-09-13 11:17:51,427] ==================
```
And each time the downloading had to restart from scratch. 

## Solution

Ideally downloading would use a robust method that would keep/cache stuff that's already downloaded and resume if the download doesn't complete.

**Comment by JacksonMaxfield** [comment]
1. if you are having trouble downloading resources feel free to open a PR and use GitHub Actions for testing
2. going to transfer this issue to Quilt (the service we use to manage our test resources)

**Comment by JacksonMaxfield** [comment]
Err I guess I can't transfer the issue but will ping @akarve for input

**Comment by akarve** [comment]
Issue filed to @sir-sigurd, who will circle back with a resolution
