### ISSUE TITLE
Failing test for Windows Python 3.10 even after adding bugfix/windows-tests-fix #41

### ISSUE THREAD

**Issue by christinab12** [AllenCellModeling/napari-aicsimageio#45]
Hi, 

## Description
I'm developing my own napari plugin using the [cookiecutter-napari-plugin](https://github.com/napari/cookiecutter-napari-plugin) template. My plugin also requires napari and napari-aicsimageio (latest release). My GitHub tests are failing for Windows and Python 3.10.

## Reproduction
My GitHub tests are failing for Windows and Python 3.10 [windows-latest py3.10](https://github.com/AllenCellModeling/napari-aicsimageio/issues/new?assignees=&labels=&template=bug_report.md&title=#logs) due to an error in installing JPype1. This only happens when I include napari-aicsimageio in my setup file (tests pass with napari[all] dependency). I tried to run with suggestion  in https://github.com/AllenCellModeling/napari-aicsimageio/pull/41 so by changing 
```commands = pytest -v --color=yes --cov=napari_organoid_counter --cov-report=xml```
to
```commands = python -m  pytest -v --color=yes --cov=napari_organoid_counter --cov-report=xml```
in my tox.ini file but the test still fails.

**Comment by JacksonMaxfield** [comment]
Hello @christinab12! Might just need to say "the plugin doesn't work on 3.10 yet" unfortunately :/ -- we don't publish `aicsimageio` on Python 3.10 yet because of an upstream dependency issue: https://github.com/AllenCellModeling/aicsimageio/issues/373

But this is a good reminder. I will ping the maintainers again tomorrow.

**Comment by christinab12** [comment]
Hi @JacksonMaxfield thanks for letting me know - I missed that! I will remove Python 3.10 then for now from by testing environment and close this for now
