### ISSUE TITLE
current sdist broken :/ lacking manifest

### ISSUE THREAD

**Issue by tlambert03** [AllenCellModeling/napari-aicsimageio#53]
## Description
Looks like the sdist (but not the wheel) for v0.7.0 is lacking the `napari.yaml` manifest.  This means that pip installs will work, but conda installs will not (since conda rebuilds from the sdist).  I could have sworn I checked for this in #49  ... but I dunno, maybe I looked at the wheel?

Anyway, I just double checked that on main, if you run `python -m build`, both the `sdist` and `wheel` archives that get dropped into the `dist/` folder contain the `napari.yaml` file (and now we also have `check-manifest` tests, which will also make sure of it).  So @evamaxfield ... would you mind releasing 0.7.1?

**Comment by evamaxfield** [comment]
I'm out for the day. Will release later tonight!

**Comment by tlambert03** [comment]
no worries! :) enjoy your day

**Comment by evamaxfield** [comment]
Had to update the bumpversion.cfg but v0.7.1 was just pushed. Should be out within ~30 minutes
