### ISSUE TITLE
broken with recent aicsimageio release

### ISSUE THREAD

**Issue by tlambert03** [AllenCellModeling/napari-aicsimageio#55]
## Description

i think https://github.com/AllenCellModeling/aicsimageio/pull/425/files broke our tests here (used git bisect)

**Comment by evamaxfield** [comment]
I am rerunning CI. I believe it was actually the upstream fsspec release. aicsimageio v4.9.1 fixes that upstream (your bisect)

CI rerun here: https://github.com/AllenCellModeling/napari-aicsimageio/actions/runs/2790743869

**Comment by tlambert03** [comment]
ok sounds good!  I was actually testing it locally.  but if you're on it and ci is passing, all good!

**Comment by evamaxfield** [comment]
Ah yea. Just upgrade base AICSImageIO to 4.9.1 and it _should_ be back to normal
