### ISSUE TITLE
Layer names

### ISSUE THREAD

**Issue by MosGeo** [AllenCellModeling/napari-aicsimageio#57]
## Use Case
When loading simple images without information attached, e.g. jpg, png, and so on, the layer name is just `image:0`. I would expect napari-aicsimageio to use the filename as a layer name if no metadata is found in the file.

## Solution
Layer name should be taken from the metadata if it is available. If it is not available, filename (without extension) can be used.

**Comment by psobolewskiPhD** [comment]
This is the behavior of the default, builtins napari reader. I think it's a good idea!
I'll see if it's something I can implement.
