### ISSUE TITLE
Updated Citation

### ISSUE THREAD

**Issue by evamaxfield** [AllenCellModeling/napari-aicsimageio#62]
Opening and closing this issue as a method to send you both (@tlambert03, @psobolewskiPhD) a message.

I updated the [citation on the README](https://github.com/AllenCellModeling/napari-aicsimageio#citation) after updating it on the core library. It now has the new AICSImageIO citation AND a citation with your names on it for just this plugin. Users can cite what they want, either or both.

I hope this is okay. If you want me to remove your name let me know.

**Comment by psobolewskiPhD** [comment]
❤️ Eva!

... but my contributions are so minor that in no way do they warrant mention in a citation!

**Comment by evamaxfield** [comment]
> :heart: Eva!
> 
> ... but my contributions are so minor that in no way do they warrant mention in a citation!

I strongly disagree. Even if you didn't make too many code contributions (which is false, you did), you pushed me to make changes and discussed changes. If we don't allow that, how would we ever allow our advisors on papers :joy:

**Comment by psobolewskiPhD** [comment]
(wtf is the order of the GitHub reactions based on? Certainly not my clicking!)
