### ISSUE TITLE
Getting image scale from napari viewer

### ISSUE THREAD

**Issue by christinab12** [AllenCellModeling/napari-aicsimageio#65]
Hi,

I'm using your plugin to load images for my own [plugin](https://www.napari-hub.org/plugins/napari-organoid-counter). For this, I get the image and scale, once loaded directly from the viewer: 
```
img_data = self.viewer.layers[self.image_layer_name].data
img_scale = self.viewer.layers[self.image_layer_name].scale
```
For czi data the scale is correctly taken as the physical distance of X, Y (visible in the side panel under images->pixels).
For tif data (previously created with _aicsimageio.writers.ome_tiff_writer.OmeTiffWriter_) the scale is always 1.0 even though the correct resolution is visible also for this image type in the side panel.

How can I get the correct resolution also for tiff images?

Thanks!

**Comment by psobolewskiPhD** [comment]
Eep, this got overlooked.
@christinab12 I think your issue isn't related to this plugin, per se, but upstream to the `aicsimageio` library that does the actual reading. 
It looks like the tiff reader doesn't provide the `physical_pixel_sizes` attribute, so the scale isn't set. There's a PR which I think should fix this https://github.com/AllenCellModeling/aicsimageio/pull/456

**Comment by christinab12** [comment]
Thanks @psobolewskiPhD, makes sense! So I will wait for newer version :)

**Comment by psobolewskiPhD** [comment]
That PR has been merged: https://github.com/AllenCellModeling/aicsimageio/pull/456
So you can either install aicsimageio from git or wait for a release!
