### ISSUE TITLE
Opening CZI Opens Multiple Windows

### ISSUE THREAD

**Issue by gatordevin** [AllenCellModeling/napari-aicsimageio#8]
## Description
With this Napari Plugin installed in python3 opening, a .czi image causes new napari windows to open. These images are duplicates of the initial window I used to browse and open the file. 

## Expected Behavior
I would expect the CZI image to open properly and have two sliders at the bottom one for the channel and one for the z depth of the image. My initial window also has the default skimage astronaut but napari should be able to handle this and just place the czi image as a new channel on top of this image. I was able to successfully open a czi image using the example code provided in your **napari_x_pylibczi** repository. I could write a custom plugin based on this but I would love to be able to use the one you all have already created.

## Reproduction
`from skimage import data`
`import napari`
`import numpy as np`

`with napari.gui_qt():`
    `viewer = napari.view_image(data.astronaut(), rgb=True)`

## Environment
Python version 3.8.5

Ubuntu 20.04
Napari version 0.3.5
IDE - Visual Studio Code

**Comment by gatordevin** [comment]
After closing all the windows that pop up except for the initial one the images appear. However, rather than appear as one multidimensional array image with two sliders as I would expect they show up as two different images channel one and channel two, and are both hidden until I show them.

**Comment by JacksonMaxfield** [comment]
Hey @gatordevin 

I am not sure I follow what you mean as I could not reproduce. Any chance you could record a video or GIF of the behavior you are observing and share?

My attempt to reproduce: [YouTube](https://youtu.be/4QOFzFQhxmw)

Can you also post which version of `napari-aicsimageio` you have installed as well?

**Comment by gatordevin** [comment]
Hey, @JacksonMaxfield thanks for the quick reply!
My napari-aicsimageio version is 0.1.3
I recorded a quick GIF of what is happening.
![Bug](https://user-images.githubusercontent.com/5672778/101229857-48c46680-3670-11eb-869f-569e18ddd214.gif)

**Comment by JacksonMaxfield** [comment]
Woah. Fascinating.

Can you try starting napari in a terminal not connected to VSCode?

And which GUI lib are you using? `PyQT5` or something else?

**Comment by gatordevin** [comment]
It is definitely an interesting problem!

I am using the default for Napari which I believe is PyQT5 so yes.

Even weirder is that running from a terminal not through a python script it works perfectly.
![Bug_2](https://user-images.githubusercontent.com/5672778/101230135-9e4d4300-3671-11eb-9048-7cd9ec234522.gif)

**Comment by JacksonMaxfield** [comment]
@sofroniewn sorry to drag you in to this thread but have you ever seen anything like this?

**Comment by gatordevin** [comment]
`from skimage import data`
`import napari`
`import numpy as np`

`with napari.gui_qt():`
    `viewer = napari.view_path("/home/techgarage/Projects/Max` `Planck/NapariFrontEnd/s_1_t_5_c_1_z_1.czi")`

Also tried starting the Napari viewer using the view_path function and created the same issues as in the first Gif.

**Comment by sofroniewn** [comment]
Wow, this is fascinating! Havn't seen this before. A couple questions, does this also happen if you drag and drop a png / tiff into napari? What if you uninstall `napari-aicsimageio`?

I will note that you're on napari `0.3.5`, and we're now on `0.4.2` - if you could try updating to the latest with `pip install napari -U` (if  `napari-aicsimageio` is compatible with the latest). That might fix it too. Some libraries may have gotten out of sync.

**Comment by gatordevin** [comment]
Hey @sofroniewn. Dragging and dropping PNGs or TIFFs works flawlessly. I just uninstalled  `napari-aicsimageio` and then reinstalled (no success). I also tried uploading to the latest `0.4.2` version of napari. Still, no success whether opening from the file explorer, through view_path, or through drag and drop it creates the same issue. The only thing that works is running napari from the terminal. Thank you guys for all the help.

**Comment by JacksonMaxfield** [comment]
To clarify, you uninstalled `napari-aicsimageio` and tried opening a PNG / TIFF and everything worked as expected (i.e. you _didn't see multiple windows like in the above GIF)?

If that is the case it's definitely either a bug in this library or a weird interaction with the hook spec potentially?

**Comment by gatordevin** [comment]
Yes, I uninstalled `napari-aicsimageio` and was able to drag and drop a PNG / TIFF with no problem. That also worked with the plugin installed as long as I changed the plugin call order to have the builtins first. Otherwise, the plugin tried to open the PNG / TIFF and created the same multi-window opening issue. What is also weird is exactly four new windows are created every time regardless of the image size or type.

**Comment by JacksonMaxfield** [comment]
Hm. I will try to take a look at this more deeply over the weekend. Likely Sunday unfortunately.

At the very least what you may be able to do in place as a patch until this is resolved is:

```python
from aicsimageio import AICSImage
import napari

img = AICSImage("file.czi")

with napari.gui_qt():
    napari.view_image(img.data)  # or img.dask_data whichever you need to load the image
```

Could you share the file for my testing this weekend?

**Comment by gatordevin** [comment]
Awesome thank you so much!
Currently working on a deep learning plugin that supports not just testing and running models but also training so plenty of other things to do. I attached the CZI file below I pulled it off one of your other repositories.

Thought I may as well put my code in there as well even though it's just test code and I only got 6 lines deep.

Also, I don't know if this is too much to ask or if its already a feature but is it possible to add the option to load the czi image into a single image layer that has a slider for each channel and a slider for each z height rather than load as two separate layers.
[s_1_t_5_c_1_z_1.zip](https://github.com/AllenCellModeling/napari-aicsimageio/files/5646353/s_1_t_5_c_1_z_1.zip)
[test.zip](https://github.com/AllenCellModeling/napari-aicsimageio/files/5646358/test.zip)

**Comment by JacksonMaxfield** [comment]
> I attached the CZI file below I pulled it off one of your other repositories.

Hah. I saw the filename format and figured it was one of ours but too many files to keep track of.

> Also, I don't know if this is too much to ask or if its already a feature but is it possible to add the option to load the czi image into a single image layer that has a slider for each channel and a slider for each z height rather than load as two separate layers.

I am personally open to it. I think that should be a relatively minor change. I especially think it makes sense in the context of our upcoming aicsimageio 4.0 release which drastically changes how we handle the "Scenes" of a file and it may make more sense to use the "Napari Images" for "File Format Scenes / Images". I can have answer for that one on Monday probably. Can you open a second issue for it though?

**Comment by gatordevin** [comment]
That sounds great. I'll open one up right now. Honestly, I could probably make my plugin work with either but I think having the idea of opening all scenes in one layer would be generally useful.

**Comment by heeler** [comment]
I tried to reproduce this on a manjaro (linux) box but it behaves normally. 
@JacksonMaxfield I'm really curious if you can on your ubuntu box.

**Comment by gatordevin** [comment]
I tried making a virtual environment to put my project and dependencies in just to be sure I didn't have any conflicts in my main environment. I installed the exact same versions that @JacksonMaxfield used in his video trying to reproduce the error and I had the same issue.

**Comment by JacksonMaxfield** [comment]
I have been trying different variants of packages and such for the past hour. I unfortunately still can't reproduce on my machine.

I have tried current `napari`, original `napari` version linked in your first issue comment (0.3.5), random files, `skimage` astronaut, the specific CZI you provided (`s_1_t_5_c_1_z_1.czi` from our tests sets), different Python versions, etc.

You said you made a new env and installed. Can I get a copy+paste of your `pip freeze` from your env?

And are you using base Ubuntu or a different distro? I can't reproduce on Mac, Ubuntu Budgie (20.04), and @heeler said he couldn't reproduce on Manjaro Linux.

**Comment by JacksonMaxfield** [comment]
I CAN REPRODUCE THE BUG.

Somehow I skipped over this comment:
> Even weirder is that running from a terminal not through a python script it works perfectly.

I tossed the code into a temp python script and yup weirdness ensues. Will try to figure out what is going on.

**Comment by JacksonMaxfield** [comment]
Alright @gatordevin 

I believe I have a fix for you but before I make a PR can you give it a try?

To do so please:
```bash
git clone https://github.com/AllenCellModeling/napari-aicsimageio.git
cd napari-aicsimageio
git checkout bugfix/remove-dask-process-created-windows
pip install .
```

Then try out your Python script again.

Let me know if the branch works and if so I will merge and release a new version of this library!

**Comment by gatordevin** [comment]
Hey, awesome to hear. It works perfectly now when opening the demo file. However, when attempting to open a multi-channel image it throws this error. I will attach the image I attempted to open. Thank you for your help though it looks like the problem is almost solved.
[A1-2 zstack  20X.zip](https://github.com/AllenCellModeling/napari-aicsimageio/files/5649934/A1-2.zstack.20X.zip)

Traceback (most recent call last):
  File "/home/techgarage/Projects/Max Planck/NapariFrontEnd/napari-deep/lib/python3.8/site-packages/napari/layers/utils/stack_utils.py", line 90, in split_channels
    i_kwargs[key] = next(val)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/techgarage/Projects/Max Planck/NapariFrontEnd/napari-deep/lib/python3.8/site-packages/napari/_qt/qt_viewer.py", line 456, in _open_files_dialog
    self.viewer.open(filenames)
  File "/home/techgarage/Projects/Max Planck/NapariFrontEnd/napari-deep/lib/python3.8/site-packages/napari/components/viewer_model.py", line 840, in open
    self._add_layers_with_plugins(
  File "/home/techgarage/Projects/Max Planck/NapariFrontEnd/napari-deep/lib/python3.8/site-packages/napari/components/viewer_model.py", line 908, in _add_layers_with_plugins
    new = self._add_layer_from_data(*_data)
  File "/home/techgarage/Projects/Max Planck/NapariFrontEnd/napari-deep/lib/python3.8/site-packages/napari/components/viewer_model.py", line 980, in _add_layer_from_data
    layer = add_method(data, **(meta or {}))
  File "/home/techgarage/Projects/Max Planck/NapariFrontEnd/napari-deep/lib/python3.8/site-packages/napari/components/viewer_model.py", line 772, in add_image
    layerdata_list = split_channels(data, channel_axis, **kwargs)
  File "/home/techgarage/Projects/Max Planck/NapariFrontEnd/napari-deep/lib/python3.8/site-packages/napari/layers/utils/stack_utils.py", line 92, in split_channels
    raise IndexError(
IndexError: Error adding multichannel image with data shape (3, 7, 2856, 2856).
Requested channel_axis (3) had length 2856, but the 'name' argument only provided 3 values.

**Comment by JacksonMaxfield** [comment]
@gatordevin thanks for testing it! This should now be patched. Want update the branch and give it another quick try?

```bash
git fetch
git pull
```

**Comment by gatordevin** [comment]
It works perfectly. Thank you so much for all your help!

**Comment by JacksonMaxfield** [comment]
Great! I will release `napari-aicsimageio==0.2.0` tomorrow afternoon after it goes through the review process.

**Comment by JacksonMaxfield** [comment]
`napari-aicsimageio==0.2.0` is now released!

Sorry for the delay in getting this out. Was waiting until I could include Python 3.9 support as well.

Hopefully this resolves all the issues now :+1:
