### ISSUE TITLE
Load all channels into the same image layer

### ISSUE THREAD

**Issue by gatordevin** [AllenCellModeling/napari-aicsimageio#9]
## Feature
Give Aicsimageio plugin the ability to open all scenes of a CZI image into a single Napari Image Layer as a multi-dimensional image rather than automatically splitting each scene into a different layer by default.

**Comment by JacksonMaxfield** [comment]
Hey @gatordevin we discussed this in our meeting today and ultimately decided that the current default behavior of aicsimageio (splitting channels out into different layers) makes sense to us and that we won't be changing that behavior right now.

We would however accept a PR if you or anyone else wants to add functionality to the plugin that allows for that behavior to be determined on image load or from a check box or some other widget on the napari viewer itself.

I think in general I would love to make a lot of changes like the above "viewer config settings", metadata viewing widgets / tables, and more, but that will be a long way out and so I am putting this as very low priority until I get around to that type of work.

---

Side note, I think there was confusion in terminology. "Scenes" refers to wholely separate images in the same file (i.e. different dtypes, shape, etc.), if you are using `aicsimageio>=3<4` this is the `S` dimension. "Channels" refers to separate pixel data blocks that are of consistant shape and size to a spatial Z Y X dimensions in the same Scene. File formats and naming standards :shrug:

**Comment by psobolewskiPhD** [comment]
@gatordevin You may find what you need when #27 is merged. You will be able to control whether channels are unpacked and you can open multiple scenes. Then select the image layers, right click, and Merge to Stack will give you one stack.
